# Generated by Django 4.1.7 on 2023-03-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MercadoJogos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('jogo', models.CharField(max_length=30)),
                ('verificar', models.BooleanField(default=False)),
            ],
        ),
    ]
